import {
  CodeIcon,
  DeviceMobileIcon,
  CpuIcon,
  RocketLaunchIcon,
  TrendUpIcon,
  CloudIcon,
  LightningIcon,
  ShieldCheckIcon,
  ChartLineUpIcon,
  ArrowsClockwiseIcon,
  GearSixIcon,
  DatabaseIcon,
  LockKeyIcon,
  UsersThreeIcon,
  CheckCircleIcon,
  SparkleIcon,
  BrowserIcon,
  TerminalWindowIcon,
  HeadsetIcon,
  GlobeIcon,
  GraphIcon,
  PuzzlePieceIcon,
  RobotIcon,
  TreeStructureIcon,
  HardDrivesIcon,
  InfinityIcon,
  CaretRightIcon,
  ArrowRightIcon,
  CheckIcon,
  MagnifyingGlassIcon,
  PhoneIcon,
  EnvelopeSimpleIcon,
} from "@phosphor-icons/react/dist/ssr";

export const ServiceIconsMap = {
  // Core Services
  CodeIcon,
  DeviceMobileIcon,
  CpuIcon,
  RocketLaunchIcon,
  TrendUpIcon,
  CloudIcon,

  // Benefits & Features
  LightningIcon,
  ShieldCheckIcon,
  ChartLineUpIcon,
  ArrowsClockwiseIcon,
  GearSixIcon,
  DatabaseIcon,
  LockKeyIcon,
  UsersThreeIcon,
  CheckCircleIcon,
  SparkleIcon,
  BrowserIcon,
  TerminalWindowIcon,
  HeadsetIcon,
  GlobeIcon,
  GraphIcon,
  PuzzlePieceIcon,
  RobotIcon,
  TreeStructureIcon,
  HardDrivesIcon,
  InfinityIcon,
  CaretRightIcon,
  ArrowRightIcon,
  CheckIcon,
  MagnifyingGlassIcon,
  PhoneIcon,
  EnvelopeSimpleIcon,
};

export function getServiceIcon(name, fallback = CodeIcon) {
  return ServiceIconsMap[name] || fallback;
}
